name: Automatic merging

on:
  push:
    branches:
      - stage
      - hotfix
      - master

env:
  BRANCH_TO_MERGE: ${{ github.ref }}
  BASE_BRANCH: ${{ github.ref }}

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set Branch and Merge banch on Stage -> Dev
        if: github.ref == 'refs/heads/stage'
        run: |
          echo "BRANCH_TO_MERGE=stage" >> $GITHUB_ENV
          echo "BASE_BRANCH=dev" >> $GITHUB_ENV

      - name: Merge stage into dev
        if: github.ref == 'refs/heads/stage'
        run: |
          git config user.name "sethchurch"
          git config user.email "schurch@clearpointstrategy.com"
          git checkout dev
          git merge --ff-only stage
          git push -u origin HEAD

      - name: Set Branch and Merge banch on Hotfix -> Dev
        if: github.ref == 'refs/heads/hotfix'
        run: |
          echo "BRANCH_TO_MERGE=hotfix" >> $GITHUB_ENV
          echo "BASE_BRANCH=dev" >> $GITHUB_ENV

      - name: Merge hotfix into dev
        if: github.ref == 'refs/heads/hotfix'
        run: |
          git config user.name "sethchurch"
          git config user.email "schurch@clearpointstrategy.com"
          git checkout dev
          git merge --ff-only hotfix
          git push -u origin HEAD

      - name: Set Branch and Merge banch on Master -> Stage
        if: github.ref == 'refs/heads/master'
        run: |
          echo "BRANCH_TO_MERGE=master" >> $GITHUB_ENV
          echo "BASE_BRANCH=stage" >> $GITHUB_ENV

      - name: Merge master into stage
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "sethchurch"
          git config user.email "schurch@clearpointstrategy.com"
          git checkout stage
          git merge --ff-only master
          git push -u origin HEAD

      - name: Set Branch and Merge banch on Stage -> Dev
        if: github.ref == 'refs/heads/master'
        run: |
          echo "BRANCH_TO_MERGE=stage" >> $GITHUB_ENV
          echo "BASE_BRANCH=dev" >> $GITHUB_ENV

      - name: Merge stage into dev after master merge
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "sethchurch"
          git config user.email "schurch@clearpointstrategy.com"
          git checkout dev
          git merge --ff-only stage
          git push -u origin HEAD

      - name: create pull request
        if: failure()
        run: gh pr create -B ${{ env.BASE_BRANCH }} -H ${{ env.BRANCH_TO_MERGE }} --title 'Merge ${{ env.BRANCH_TO_MERGE }} into ${{ env.BASE_BRANCH }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_KEY }}
